# Generated by Django 3.1.7 on 2021-04-06 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookpdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='bookpdf'),
            preserve_default=False,
        ),
    ]
